In [13]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [14]:
x.requires_grad_(True) # equivalent to x = torch.arange(4.0, requires_grad=True)
x.grad # defalut is None

In [15]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()
x.grad # dy/dx

tensor([ 0.,  4.,  8., 12.])

In [19]:
# by default, pytorch will accumulate gradients, we need to clear the previous values
x.grad.zero_()
y = x.sum() # y = x1 + x2 + x3 + x4
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [21]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [25]:
# detach calculations
x.grad.zero_()
y = x * x
u = y.detach() # treat u as a constant
z = u * x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [27]:
# Gradient calculation of Python control flow
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [28]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a # f(a) is piecewise linear, so f(a) = k * a

tensor(True)