In [1]:
import torch
import torch.nn.functional as F
from torch import nn

### layer without parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [9]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

### layer with parameters

In [11]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [12]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.9583, -0.5032, -1.1015],
        [-1.3138, -0.9716, -0.8633],
        [ 0.3364,  0.5687,  0.3027],
        [ 1.0614, -0.3714, -0.3782],
        [ 1.0730, -0.0791,  1.2005]], requires_grad=True)

In [13]:
linear(torch.rand(2, 5))

tensor([[0.7617, 0.0375, 0.6840],
        [1.7689, 0.2242, 0.1418]])

In [14]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])